name = "portfolio"
type = "webpack"  # or leave it out for static site

account_id = "45b13b12feed387ccdd32042ebe9cbf8"
compatibility_date = "2024-06-11"  # use current date

[site]
bucket = "./dist"
entry-point = "."  # required for `site`
